### ISSUE TITLE
Conda requirements are OSX specific

### ISSUE THREAD

**Issue by AymenQ** [Tarteel-io/Tarteel-ML#16]
Conda requirements are currently OSX specific -- either a simpler requirements file should be created by hand (without pinning each individual dependency unnecessarily), or a separate requirements file should be made for Linux systems.

**Comment by tifa2UP** [comment]
+1. Do you want to pick up that task @AymenQ?

**Comment by AymenQ** [comment]
Yep I'm happy to.
