### ISSUE TITLE
Some demographic metadata missing from Tarteel Dataset CSV

### ISSUE THREAD

**Issue by abidlabs** [Tarteel-io/Tarteel-ML#19]
Recordings are being uploaded prior to any demographic info submitted (ex. people submit 5 ayahs and then put their demographics).

Potential hotfix is creating a small script to link all AnnotatedRecording objects with the same session_id as a DemographicInformation (which I believe is technically being done here: https://github.com/Tarteel-io/tarteel-api/blob/504ffb933c6b328b888714b5fb20f35f138a6b41/audio/views.py#L432)

**Comment by khanh111** [comment]
This has been fixed, right? If so, please close with a reference to the solution commit.

**Comment by piraka9011** [comment]
@khanh111 This was resolved in the tarteel-api repo.
The commit is a bit too deep to find :slightly_smiling_face:
