### ISSUE TITLE
get error IndexError: too many indices for array

### ISSUE THREAD

**Issue by Mohamedmtc** [Tarteel-io/Tarteel-ML#22]
i made audio data set from 10 quran readers for each aya
so i have 10 audio files for each aya with sample rate 32000 hz in wav format also i passed all audio files on audio checking function in your download script
so now i have 61382 audio file 10 files foreach aya
so now i tried to run script Sequence-to-Sequence Model in Keras 
where i prepared every thing as you build your system 
- Data/one-hot.pkl
-.outputs/mfcc

but in your script you used 
def build_dataset(local_coefs_dir='../.outputs/mfcc', surahs=[1], n=100):
i changed it to
def build_dataset(local_coefs_dir='../.outputs/mfcc', surahs=[2], n=100):

but i got this error
"IndexError: too many indices for array"
 while executing this function
"convert_list_of_arrays_to_padded_array"
in this line
"padded_array[a, :r, :c] = arr"

and this is the values stored in memory
shape (1361, 13)
max_shape [13459]
padded_array (100,13459)

**Comment by khanh111** [comment]
These files are in the middle of a refactor. Please follow #27 for updates.
