### ISSUE TITLE
Downloading Surah Al-Fatihah only took long time

### ISSUE THREAD

**Issue by SamahZaro** [Tarteel-io/Tarteel-ML#25]
I was trying to download and preprocess Al-Fatiha. Here my commands:

```
git clone https://github.com/Tarteel-io/Tarteel-ML.git
cd Tarteel-ML/
git cherry-pick 624c46b
conda env create -f environment.yml
conda activate tarteel-ml
python download.py -s 1
```

I applied this [commit](https://github.com/Tarteel-io/Tarteel-ML/commit/624c46b6e92f4eb6a4977da3e4e6979822440ece) to fix invalid wave header issue and make it download. However, it took long time for one short surah! Is this normal?

![image](https://user-images.githubusercontent.com/16727231/60755198-f1dadd80-9ff4-11e9-971a-d02925b12479.png)

**Comment by AymenQ** [comment]
How long does it take for you? Takes around 6-7 minutes for me (and my connection is ~45Mbps down). It's only 61MB, but the scripts also try to check each file to see if they have speech (using webrtcvad), and in a lot of cases it needs to convert them from mpeg-4 to WAV as well.

**Comment by AymenQ** [comment]
Hi, how long did it take for you? It takes around ~8 minutes for me (my connection is 50Mbps down). It's (only) 243 MB, but for each audio file (221 of them) it checks for voice content (with webrtcvad), and in a lot of cases it needs to convert them from mpeg to wav.

**Comment by SamahZaro** [comment]
My download speed isn't that good. Anyway, wouldn't it be good to make a compressed version available? containing preprocessed .wav of .flac files?

**Comment by SamahZaro** [comment]
The checking and conversion are what taking time. It took more than 00:15
assuming I am going to download the whole Quran, will it take ~ 600 * 00:15 minutes?!

**Comment by AymenQ** [comment]
I agree, it does take quite a long time. I think at the moment it's not such a big issue, since we don't need to use the entire dataset when figuring out initial models and architectures. There was an idea floating around a while ago of uploading all the preprocessed MFCCs to an amazon bucket (which would speed things up), but I don't think that's be done yet.

**Comment by SamahZaro** [comment]
> 
> There was an idea floating around a while ago of uploading all the preprocessed MFCCs to an amazon bucket (which would speed things up), but I don't think that's be done yet.

Good to know.

I have provided the entire [auto-evaluated Tarteel.v1 dataset](https://github.com/Tarteel-io/Tarteel-ML/wiki/Tarteel-v1-Dataset#automatic-evaluation) on [my drive](https://drive.google.com/open?id=1p-HNPdUUqjpX43x7ivpg3vofb1D-USbU) in compressed version (Surah by Surah). The dataset contains audio files converted to valid wave and VAD removed.

**Comment by SamahZaro** [comment]
> 
> There was an idea floating around a while ago of uploading all the preprocessed MFCCs to an amazon bucket (which would speed things up), but I don't think that's be done yet.

Good to know.

Just in case this can help someone else, I have provided the entire [auto-evaluated Tarteel.v1 dataset](https://github.com/Tarteel-io/Tarteel-ML/wiki/Tarteel-v1-Dataset#automatic-evaluation) on [my drive](https://drive.google.com/open?id=1p-HNPdUUqjpX43x7ivpg3vofb1D-USbU) in compressed version (Surah by Surah).

The dataset contains audio files converted to valid wave, with VAD removed. This was done using Google Colab, and it took ~7hours.

**Comment by AymenQ** [comment]
Wow, thank you very much for doing this, that's very useful. 7 hours, not too bad!

**Comment by piraka9011** [comment]
@SamahZaro could you please share your colab notebook with us? Or open a PR with your code if you'd like?

JAK!
