### ISSUE TITLE
how to generate language model?

### ISSUE THREAD

**Issue by lerndeep** [Tarteel-io/tarteel-ml#38]
I am planning to train deep speech using the Korean language.  Could you provide some guidelines about how can I create a language model?

**Comment by piraka9011** [comment]
@lerndeep I think you're in the wrong repo :)
Check out the [DeepSpeech discourse](https://discourse.mozilla.org/t/tutorial-how-i-trained-a-specific-french-model-to-control-my-robot/22830) or the official [DeepSpeech repo](https://github.com/mozilla/DeepSpeech)
