### ISSUE TITLE
the files for the fattiha overfitting experiment

### ISSUE THREAD

**Issue by Nouraaaawwad** [Tarteel-io/tarteel-ml#40]
السلام عليكم 

currently i am experimenting a quraan tutor for surat elekhlass, the same idea as surat alfatihah but with another audio set which from a known tutors. 
it seems that i have a problem with the preprocessing step : / 

can i get the files that were used for the experiment to compare it with mine? 
    train_src.txt, train_tgt.txt, val_src.txt, val_tgt.txt

thank you

**Comment by piraka9011** [comment]
Salam,
We deprecated OpenNMT internally so we no longer use it.
You can see the official documentation for an example on how the files should look like [here](https://opennmt.net/OpenNMT-py/speech2text.html).

An example file for `train_src.txt` should contain the full path to your file and would be:
```sh
/user/noura/some_folder/file1.wav
/user/noura/some_folder/file2wav
/user/noura/some_folder/file3.wav
...
```

And for `train_tgt.txt`:
```sh
ا ل ح م د ل ل ه ر ب ا ل ع ا ل م ي ن
ول ل م ط ل ق ا ت م ت ا ع ب ا ل م ع ر و ف ح ق ا ع ل ي ا ل م ت ق ي ن
...
```
Same goes for the validation files (`val`).

You can use this repo to get the text of the quran: https://github.com/semarketir/quranjson

If this resolves your issue, please mark the issue as closed.

**Comment by Nouraaaawwad** [comment]
> 
> ```shell
> ا ل ح م د ل ل ه ر ب ا ل ع ا ل م ي ن
> ول ل م ط ل ق ا ت م ت ا ع ب ا ل م ع ر و ف ح ق ا ع ل ي ا ل م ت ق ي ن
> ...
> ```


thank you anas for the reply 💯 
but i wonder why did you make the tgt-train file in Arabic format ? is the model going to recognize it when the user speak ? 
Also if i put it in Arabic would it be the this:
_الحمد<space>لله<space>رب<space>العالمين 
الرحمن<space>الرحيم
مالك<space>يوم<space>الدين_
.....
or like this ::
_ا ل ح م د<space>ل ل خ<space> ر ب<space>ا ل ع ا ل م ي ن_
......
 ?

**Comment by piraka9011** [comment]
The target (`tgt`) files are the labels for the audio files you specified in the source (`src`) files.
So if you want the model to learn the Arabic text, you need to give it Arabic labels :)

If you want the model to learn the word features, then use the first format.
If you want the model to learn the letter features, use the second format.
Unless you have a lot of data, stick to the first format.

**Comment by Nouraaaawwad** [comment]
thank you anas .. appreciate your time
