### ISSUE TITLE
`dataset_csv_url` : A ghost argument? 

### ISSUE THREAD

**Issue by omerasif-itu** [Tarteel-io/tarteel-ml#45]
**Issue: Exception**

In `download.py`, line `103` throws exception:

> `'Namespace' object has no attribute 'dataset_csv_url'`

while changing it to `csv_url`, fixes it.

**Possible Cause:** 
 Argument mismatch?

`line 26` : `parser.add_argument('--csv-url', type=str, default=TARTEEL_V1_CSV_URL)`

`line 103` : `download_csv_dataset(args.dataset_csv_url, path_to_dataset_csv)`

**Comment by piraka9011** [comment]
This indeed looks like an issue. If you can open a PR that'd be great :)
Otherwise I'll get to it over the next few days.
