### ISSUE TITLE
How to pass a live stream of audio to the ML

### ISSUE THREAD

**Issue by Nouraaaawwad** [Tarteel-io/tarteel-ml#48]
Hello

My plan is to make a mobile application for correcting the speech of the user while reading surat Al-EKlass.
i saw your tarteel application and it is fantastic ❤️  thank you for your work.

i already did the ML speech2text with OpenNMT, but i am wondering how did you pass a live stream audio from microphone to recognize it ? My plan was after training the ML i would set up the REST server then doing a GUI. but i am stuck with the audio streaming now :/

appreciate your help..,
thank you

**Comment by piraka9011** [comment]
Noura,

Streaming is done using [websockets](https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API) which provides a continuous stream of data between some client/server.

REST APIs are good for request/response architectures that don't require realtime response.

Also, issues in this repo should ideally be related to the code in the repo :)
If you have general questions about Tarteel, you should email us at info@tarteel.io.

Please close this issue if this answers your question.

**Comment by piraka9011** [comment]
I noticed you also opened a similar issue here: https://github.com/OpenNMT/OpenNMT-py/issues/1865

It is generally good practice _not_ to cross post similar questions in multiple locations.

Like the answer there, this question outside the scope of the project.
Stackoverflow and reddit are usually good places to ask these questions.
